language: node_js
node_js:
  - v6
  - v5
  - v4
script: npm run test
after_success: cat ./test/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
